line-length = 92
target-version = "py312"

[lint]
select = ["E", "F", "I", "B", "UP", "C4", "SIM", "ARG"]
ignore = ["B008", "E501", "ARG001", "ARG002", "UP035", "SIM117"]

[lint.per-file-ignores]
"tests/*" = ["ARG001", "ARG002"]
